/*
 * LEVEL_CONVERSION - Coverting from effective level to displayed level
 */

drop table if exists mpq_data.level_conversion ;

create table mpq_data.level_conversion (
	level_conversion_id integer primary key generated by default as identity,
	rarity integer not null,
	effective_level integer not null,
	display_level integer not null
);

create unique index uk_level_conversion_rarity_efflvl on mpq_data.level_conversion(rarity, effective_level);

create unique index uk_level_conversion_rarity_dsplvl on mpq_data.level_conversion(rarity, display_level);

alter table mpq_data.level_conversion
	add constraint uk_level_conversion_rarity_efflvl
	unique using index uk_level_conversion_rarity_efflvl
;

comment on table mpq_data.level_conversion is 'Mapping the effective level from the demiurge api to the displayed level in game.';

