/*
 * LOCALE_TEXT - text strings for all data elements by language.  
 */

drop table if exists mpq_data.locale_text ;

create table mpq_data.locale_text (
	locale_text_id integer primary key generated by default as identity (cycle),
	text_key varchar(100) not null, 
	locale_language varchar(2) not null, 
	text varchar(1000) not null
);

create unique index uk_locale_text_textkey_localelang on mpq_data.locale_text(text_key, locale_language);

alter table mpq_data.locale_text
	add constraint uk_locale_text_textkey_localelang
	unique using index uk_locale_text_textkey_localelang
;

comment on table mpq_data.locale_text is 'Text snippets by language.';

