/*
 * ALLIANCE - Character ability data.
 */

drop table if exists mpq_data.player ;

create table mpq_data.player (
	player_id integer primary key generated by default as identity,
	player_name varchar(100) unique not null,
	player_guid varchar(100) not null
);

comment on table mpq_data.player is 'Local cache of player id from game APIs.';

